apiVersion: v1
kind: Pod
metadata:
  name: color123
  labels:
      app: myapp
      name: color-app
spec:
  containers:
    - name: color123
      image: shashank123
      imagePullPolicy: Never
      ports:
        - containerPort: 5000

--- 

apiVersion: v1
kind: Service
metadata:
  name: color123-service
spec:
  selector: 
      app: myapp
      name: color-app
  type: NodePort
  ports:
    - port: 5000
      targetPort: 80
      nodePort: 30008